CREATE TABLE public.skills (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    person_id integer NOT NULL,
    skill_name text NOT NULL,
    level_id integer,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz
);
CREATE INDEX idx_skills_person_id ON public.skills (person_id);
