-- Create workflow_status enum with states used by WorkFlowService
DO $$ BEGIN
  CREATE TYPE workflow_status AS ENUM (
    'QuotationPending',
    'OrderApproved',
    'InProgress',
    'WorkSubmitted',
    'Completed',
    'Cancelled'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Workflow table (one workflow per post)
CREATE TABLE IF NOT EXISTS workflow (
  id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id                   INTEGER NOT NULL REFERENCES post(id) ON DELETE CASCADE,
  status                    workflow_status NOT NULL DEFAULT 'QuotationPending',
  revision_required         BOOLEAN NOT NULL DEFAULT FALSE,
  revision_count            SMALLINT NOT NULL DEFAULT 0,
  revision_reason           TEXT NULL,
  deliverable_version       SMALLINT NOT NULL DEFAULT 0,
  deliverable_submitted_at  TIMESTAMPTZ NULL,
  deliverable_accepted      BOOLEAN NOT NULL DEFAULT FALSE,
  accepted_at               TIMESTAMPTZ NULL,
  created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enforce one workflow row per post
CREATE UNIQUE INDEX IF NOT EXISTS idx_workflow_post_unique ON workflow(post_id);
