-- Create workflow_status enum with states used by WorkFlowService
DO $$ BEGIN
  CREATE TYPE workflow_status AS ENUM (
    'QuotationPending',
    'OrderApproved',
    'InProgress',
    'PendingEmployerReview',
    'Completed',
    'Cancelled'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Workflow table (one workflow per post)
CREATE TABLE IF NOT EXISTS workflow (
  id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id                   INTEGER NOT NULL REFERENCES post(id) ON DELETE CASCADE,
  seq_number                SMALLINT NOT NULL DEFAULT 1,
  status                    workflow_status NOT NULL DEFAULT 'QuotationPending',
  revision_required         BOOLEAN NOT NULL DEFAULT FALSE,
  revision_count            SMALLINT NOT NULL DEFAULT 0,
  revision_reason           TEXT NULL,
  deliverable_version       SMALLINT NOT NULL DEFAULT 0,
  deliverable_submitted_at  TIMESTAMPTZ NULL,
  deliverable_accepted      BOOLEAN NOT NULL DEFAULT FALSE,
  accepted_at               TIMESTAMPTZ NULL,
  created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                TIMESTAMPTZ NULL
);

ALTER TABLE workflow
    ADD CONSTRAINT  workflow_seq_number_min_one CHECK (seq_number >= 1);

CREATE INDEX IF NOT EXISTS idx_workflow_post ON workflow(post_id);
CREATE INDEX IF NOT EXISTS idx_workflow_post_status ON workflow(post_id, status);