name: "\U0001F41E Bug Report"
description: Create a report to help us improve app_108jobs
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Found a bug? Please fill out the sections below. ðŸ‘
        Thanks for taking the time to fill out this bug report!
        For front end issues, use [app_108jobs](https://github.com/app_108jobsNet/app_108jobs-ui)
  - type: checkboxes
    attributes:
      label: Requirements
      description: Before you create a bug report please do the following.
      options:
        - label: Is this a bug report? For questions or discussions use https://app_108jobs.ml/c/app_108jobs_support or the [matrix chat](https://matrix.to/#/#app_108jobs:matrix.org).
          required: true
        - label: Did you check to see if this issue already exists?
          required: true
        - label: Is this only a single bug? Do not put multiple bugs in one issue.
          required: true
        - label: Do you agree to follow the rules in our [Code of Conduct](https://join-app_108jobs.org/docs/code_of_conduct.html)?
          required: true
        - label: Is this a backend issue? Use the [app_108jobs-ui](https://github.com/app_108jobsNet/app_108jobs-ui) repo for UI / frontend issues.
          required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A summary of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Describe the steps to reproduce the bug.
        The better your description is _(go 'here', click 'there'...)_ the fastest you'll get an _(accurate)_ resolution.
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: technical
    attributes:
      label: Technical Details
      description: |
        - Please post your log: `sudo docker-compose logs > app_108jobs_log.out`.
        - What OS are you trying to install app_108jobs on?
        - Any browser console errors?
    validations:
      required: true
  - type: input
    id: app_108jobs-backend-version
    attributes:
      label: Version
      description: Which app_108jobs backend version do you use? Displayed in the footer.
      placeholder: ex. BE 0.17.4
    validations:
      required: true
  - type: input
    id: app_108jobs-instance
    attributes:
      label: app_108jobs Instance URL
      description: Which app_108jobs instance do you use? The address
      placeholder: app_108jobs.ml, app_108jobs.world, etc
