name: "? Question"
description: General questions about app_108jobs
title: "Question: "
labels: ["question", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        For questions or discussions use https://app_108jobs.ml/c/app_108jobs_support or the [matrix chat](https://matrix.to/#/#app_108jobs:matrix.org).

        Have a question about how app_108jobs works?
        Please check the docs first: https://join-app_108jobs.org/docs/en/index.html
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What's the question you have about app_108jobs?
    validations:
      required: true
