CREATE TABLE public.certificates (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    person_id integer NOT NULL,
    name text NOT NULL,
    achieved_date date NOT NULL,
    expires_date date,
    url varchar(255),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz
);
CREATE INDEX idx_certificates_person_id ON public.certificates (person_id);
