ALTER TABLE community
DROP COLUMN IF EXISTS group_id,
DROP COLUMN IF EXISTS path,
DROP COLUMN IF EXISTS subtitle,
DROP COLUMN IF EXISTS slug,
DROP COLUMN IF EXISTS active,
DROP COLUMN IF EXISTS is_new;
