-- Create language_profile table for person language proficiencies
-- Ensure required extension for case-insensitive text
CREATE EXTENSION IF NOT EXISTS citext;

DO $$ BEGIN
  CREATE TYPE language_level AS ENUM (
    'native',
    'near_native',
    'advanced',
    'upper_intermediate',
    'intermediate',
    'pre_intermediate',
    'beginner'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE language_profile (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id   INTEGER      NOT NULL REFERENCES person(id) ON DELETE CASCADE,
  lang        CITEXT       NOT NULL,               -- e.g., 'en', 'th', 'vi', 'en-US'
  level_name  language_level NOT NULL DEFAULT 'beginner',
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ
);

-- Indexes
CREATE INDEX idx_language_profile_person_id ON language_profile(person_id);
CREATE INDEX idx_language_profile_lang ON language_profile(lang);

-- Ensure one row per person per language (case-insensitive via CITEXT)
CREATE UNIQUE INDEX idx_language_profile_person_lang ON language_profile(person_id, lang);